// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcSCW04M0MYZlrI3n5XR9zjl-Km93mRjU',
    appId: '1:256037788100:web:38d1106d3f0fa4a6806c91',
    messagingSenderId: '256037788100',
    projectId: 'controlador-financeiro-pessoal',
    authDomain: 'controlador-financeiro-pessoal.firebaseapp.com',
    storageBucket: 'controlador-financeiro-pessoal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuKi7pgKDPCrFjO9Mrfq2aBXztCGFiOw',
    appId: '1:256037788100:android:a242a2f69b8d799c806c91',
    messagingSenderId: '256037788100',
    projectId: 'controlador-financeiro-pessoal',
    storageBucket: 'controlador-financeiro-pessoal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdGjrHjAONZy5IRTri8L0nNo9UOYZHr4',
    appId: '1:256037788100:ios:72d5188460679377806c91',
    messagingSenderId: '256037788100',
    projectId: 'controlador-financeiro-pessoal',
    storageBucket: 'controlador-financeiro-pessoal.appspot.com',
    iosClientId: '256037788100-rutmd5p901gqnase5frni4m43cj5o77s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoControleFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDdGjrHjAONZy5IRTri8L0nNo9UOYZHr4',
    appId: '1:256037788100:ios:72d5188460679377806c91',
    messagingSenderId: '256037788100',
    projectId: 'controlador-financeiro-pessoal',
    storageBucket: 'controlador-financeiro-pessoal.appspot.com',
    iosClientId: '256037788100-rutmd5p901gqnase5frni4m43cj5o77s.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoControleFinanceiro',
  );
}
